CREATE TABLE IF NOT EXISTS ComplianceReport (
  ReportID VARCHAR(20) PRIMARY KEY, -- Changed from INT AUTO_INCREMENT to VARCHAR(20)
  ReportName VARCHAR(150) NOT NULL,
  ReportType VARCHAR(50) NOT NULL,
  PeriodLabel VARCHAR(50) NOT NULL,
  PeriodStart DATE NOT NULL,
  PeriodEnd DATE NOT NULL,
  DueDate DATE NOT NULL,
  Status VARCHAR(20) NOT NULL DEFAULT 'Upcoming',
  SubmittedAt DATETIME NULL,
  SubmittedByUserID VARCHAR(20) NULL, -- Changed from INT to VARCHAR(20)
  FileName VARCHAR(255) NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (SubmittedByUserID) REFERENCES User(UserID)
);