CREATE TABLE IF NOT EXISTS PasswordResetToken (
  TokenID VARCHAR(20) PRIMARY KEY, -- Changed from INT AUTO_INCREMENT to VARCHAR(20)
  UserID VARCHAR(20) NOT NULL,      -- Changed from INT to VARCHAR(20)
  TokenHash VARCHAR(128) NOT NULL,
  ExpiresAt DATETIME NOT NULL,
  UsedAt DATETIME NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserID) REFERENCES User(UserID),
  INDEX idx_token_hash (TokenHash)
);