CREATE TABLE IF NOT EXISTS CompanySettings (
  CompanyID VARCHAR(20) PRIMARY KEY, -- Changed from INT to VARCHAR(20)
  FullName VARCHAR(150) NULL,
  Address VARCHAR(255) NULL,
  ContactEmail VARCHAR(150) NULL,
  Phone              VARCHAR(30) NULL,
  Branch             VARCHAR(150) NULL,
  Warehouse          VARCHAR(150) NULL,
  Brand              VARCHAR(150) NULL,
  LogoDataUrl        LONGTEXT NULL,

  TaxRate DECIMAL(5,2) NOT NULL DEFAULT 12.00,
  TaxEnabled TINYINT(1) NOT NULL DEFAULT 1,
  Currency VARCHAR(10) NOT NULL DEFAULT 'PHP',
  RoundUp TINYINT(1) NOT NULL DEFAULT 0,
  RoundDown TINYINT(1) NOT NULL DEFAULT 0,
  TwoDecimalStandard TINYINT(1) NOT NULL DEFAULT 1,

  ReceiptHeader VARCHAR(150) NULL,
  ShowLogoOnReceipt TINYINT(1) NOT NULL DEFAULT 1,
  ShowTaxBreakdown TINYINT(1) NOT NULL DEFAULT 1,
  FooterMessage VARCHAR(255) NULL,
  PrintSize VARCHAR(10) NOT NULL DEFAULT '80mm',

  AutoLogoutMinutes INT NOT NULL DEFAULT 30,
  SystemTimezone VARCHAR(50) NOT NULL DEFAULT 'Asia/Manila',
  DateFormat VARCHAR(20) NOT NULL DEFAULT 'MM/DD/YYYY',
  Language VARCHAR(10) NOT NULL DEFAULT 'en',
  Theme VARCHAR(10) NOT NULL DEFAULT 'light',

  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (CompanyID) REFERENCES Company(CompanyID)
);

ALTER TABLE CompanySettings ADD COLUMN IF NOT EXISTS Branch VARCHAR(150) NULL;
ALTER TABLE CompanySettings ADD COLUMN IF NOT EXISTS Warehouse VARCHAR(150) NULL;
ALTER TABLE CompanySettings ADD COLUMN IF NOT EXISTS Brand VARCHAR(150) NULL;



